---
title: "Basic statistical descriptive analysis"
output: pdf_document
---

```{r setup, include=FALSE}
#install.packages("knitr", dependencies = TRUE)
knitr::opts_knit$set(root.dir = dirname(dirname(rstudioapi::getActiveDocumentContext()$path)))
```

```{r, echo=FALSE}
# Get the data
dbRaw <- readRDS("./data/BeforeMissing.rds")
dbPreprocessed <- readRDS("./data/Preprocessed_data_rds.rds")
```
```{r, echo=FALSE}
# Get data metrics (rows and columns)
n<-dim(dbPreprocessed)[1]
K<-dim(dbPreprocessed)[2]
```

\section{Univariate analysis}
```{r echo = FALSE,  warning=FALSE, results = 'asis', fig.align='center'}
#sudo apt-get install libcurl4-openssl-dev
#sudo apt-get install libxml2-dev
#sudo apt-get install libfreetype6-dev
#sudo apt-get install libfontconfig1-dev
#install.packages("kableExtra", dependencies = TRUE)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(fig.pos = 'H')                   
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
descriptive<-function(X, nom, tabNum){
  if (!(is.numeric(X))){
    frecs<-table(as.factor(X), useNA="ifany")
    frecs <- sort(frecs, decreasing=TRUE)
    proportions<-frecs/n
    
    nopie <- c("detailed.industry.recode", "detailed.occupation.recode",  
               "detailed.household.and.family", "country.of.birth.father", 
               "country.of.birth.mother", "country.of.birth.self")
    
    par(mfrow=c(1,2)) # Two plots in a row
    if (!(nom %in% nopie)) pie(frecs, cex=0.6, main=paste("Pie of", nom))
    barplot(frecs, las=3, cex.names=0.7, main=paste("Barplot of", nom), col=listOfColors)
    
    cat("\\")
    cat(" \ ")
    
    cat("\\begin{center}")
    cat(paste("Number of modalities: ", length(frecs)))
    cat("\\end{center}")
    
    cat("\\")
    cat(" \ ")
   
    FaP <- data.frame(frecs, proportions)
    names(FaP) <- c(nom, "Frequency", "a", "Proportion")
    foot <- " frequency and proportion table."
    
    print(kable(subset(FaP, select= -a), align = "c") %>%
    kable_styling(latex_options = "HOLD_position"))
      
    cat("\\begin{center}")
    cat(paste("\\textbf{ Table 6.", as.character(tabNum), ". }", nom, foot, sep = ""))
    cat("\\end{center}")
     
    }else{
       par(mfrow=c(1,2)) # Two plots in a row
       
       hist(X, main=paste("Histogram of", nom), xlab=paste("Value of", nom))
       boxplot(X, horizontal=TRUE, main=paste("Boxplot of",nom))
       
       summ <-summary(X)
       
       tab <- matrix(c(summ[1], summ[2], summ[3], summ[4], summ[5], summ[6], sd(X, na.rm=TRUE), sd(X, na.rm=TRUE)/mean(X, na.rm=TRUE), sum(is.na(X))), ncol=9, byrow=TRUE)
       colnames(tab) <- c('Min.','1st Qu.','Median', 'Mean', '3rd Qu.', 'Max.', 'sd', 'vc.', 'Missing')
       rownames(tab) <- c('')
       tab <- as.table(tab)
        
       cat("\\")
       cat(" \ ")
       print(kable(tab, align = "c", booktabs = TRUE) %>%
       kable_styling(latex_options = "HOLD_position"))
       
       cat("\\begin{center}")
       cat(paste("\\textbf{ Table 6.", as.character(tabNum), ". }", nom, " extended Summary Statistics.", sep = ""))
       cat("\\end{center}")
      }
}
listOfColors<-rainbow(40)
actives<-c(1:28)
changed<-c("class.of.worker", "detailed.industry.recode", "detailed.occupation.recode", "major.industry.code", "major.occupation.code", "hispanic.origin", "country.of.birth.father", "country.of.birth.mother", "country.of.birth.self", "veterans.benefits")
par(ask=TRUE)
tabNum <- 2
for(k in actives){
  name <- names(dbPreprocessed)[k]
  
  if (k != 1) cat("\\newpage")
  
  if (k < 29)
  {
    
    tabNum <- tabNum + 1
      
    cat(paste("\\textbf{", "Variable ", k, ":", name, "}" ))
    cat("\n\n\n\n")
    descriptive(dbRaw[,k], name, tabNum)
    cat("\n\n\n\n")
  }
  
  if (name %in% changed)
  {
    
    tabNum <- tabNum + 1
    
    cat("\\newpage")
    
    cat(paste("\\textbf{", "Variable ", k, ":", name, " (CHANGED in preprocessing)}" ))
    
    cat("\n\n\n\n")
    descriptive(dbPreprocessed[,k], name, tabNum)
    cat("\n\n\n\n")
  }
}
par(ask=FALSE)
```
\newpage
\section{Bivariate analysis}
```{r echo = FALSE,  warning=FALSE, results = 'asis', fig.align='center'}
library(knitr)
library(scales)
library(kableExtra)

knitr::opts_chunk$set(fig.pos = 'H')                    
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

for (i in actives) {
  name <- names(dbPreprocessed)[i]
  if (i != 1) cat("\\newpage")
  for (j in actives) {
    if (j != i) {
	  next_name <- names(dbPreprocessed)[j]
	  if (j != 1) cat("\\newpage")
	  plot(dbPreprocessed[,i], dbPreprocessed[,next_name], pch=16, 
		   col=alpha('blue', 0.6),main= paste(name, "vs", 
		   next_name),xlab=name, ylab=next_name)
		
	  if (is.numeric(dbPreprocessed[,i]) && is.numeric(dbPreprocessed[,j])) cat(paste("Correlation between ", name, " and ", next_name, ": ", cor(dbPreprocessed[,i], dbPreprocessed[,j]))) 
    }
  }
}
```
